.circleci/config.yml
examples/running_a_dds_on_ibm_q.ipynb
qctrlopencontrols/qiskit/quantum_circuit.py
setup.py

- Using latest anaconda image again.
- Using only 2 Qiskit pakcages (terra and ibmq-providers)
- One lint issue fixed
- Source repo hyperlink in one of the notebooks corrected

Circle CI issues fix

---

qctrlopencontrols/qiskit/__init__.py
qctrlopencontrols/qiskit/constants.py
qctrlopencontrols/qiskit/quantum_circuit.py
tests/test_qiskit_sequence.py

Behaviour of `pre_post_gate_parameters` updated.
Accepts a tuple of 3 numbers.
1. Default is a tuple corresponding to a X-pi/2 rotation
2. If None, it omits any pre-post gates from the circuit
3. Otherwise it creates a `U3(...)` op as pre-post gate in the circuit

Circuit update

---

qctrlopencontrols/__init__.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/dynamic_decoupling_sequences/__init__.py
qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_dynamical_decoupling.py

Major modification - public method get_plot_data_from_segments removed and its functions are absorbed in the get_plot_formatted_arrays method
Minor modification - convert_dds_to_driven_controls->convert_dds_to_driven_control and changes related to this.

Remove get plot method

---

poetry.lock
pyproject.toml
setup.py

Changes to `poetry.lock` and `pyproject.toml` to ensure latest `qiskit` libraries are used.

Update the required version of Qiskit libraries

---

qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py

- Added an export method to driven control to allow plotting with qctrl-visualizer.
- Added an export method to dynamical decoupling sequences to allow plotting with qctrl-visualizer.
- Fixed an issue with the get_plot_formatted_arrays method in driven_controls that caused the wrong graph to be plotted in cylindrical coordinates.
@qctrl/support

Added figure compatibility with qctrl-visualizer

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
tests/test_predefined_dynamical_decoupling.py

Fixes https://q-ctrl.atlassian.net/browse/QENG-716
The solution adopted is the one described in the ticket: we invert the direction of the final pi/2-pulse when necessary. I modified the current tests to expect these inverted pulses. I also added additional tests to check if every kind of DDS produces an identity (most of these tests fail if they are run in the current master branch).
Notice that in some cases the DDS produces sigma_z rather than the identity. This happens when there is an odd number of Y and Z pi-pulses in the DDS, and these situations are identified by `expect_sigma_z = True` in the tests. Notice that the sigma_z cannot be cancelled by X pulses.
Maybe this is not a problem, as the difference between an identity and a sigma_z is just a matter of reference frame in time. …

[QENG-716] Fixing DDS that do not produce identities

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py

I was taking a look at the `convert_dds_to_driven_control` function and realized there was an inconsistency between the default values actually taken by the function and those specified in the docstring. I figured I might as well fix this, regardless of any other changes we might decide to make to the function.
(The function also tests for whether `maximum_detuning_value` is None, something that can potentially be removed given that None is not its default value after all... Unless a user chooses to set it as None)

Fixing docstrings to properly reflect default values

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
tests/test_dynamical_decoupling.py

Currently the DDS to control conversion sets the value of the detuning rates to be the same as the input detuning angle. However, the meaning of the `detunings` in the DrivenControls class is the detuning frequency rather than the detuning angle -- evidence of this is in the fact that the value of the detunings is compared to `UPPER_BOUND_DETUNING_RATE`, which is 1e10.
I'm fixing this by adopting the same procedure already used to convert the rabi_rotation into a rabi_frequency. Note that one of the unit tests had to be modified

Fixing detuning in DDS to control conversion

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
tests/test_dynamical_decoupling.py

I'm adding a test that tries to convert a sequence of pi/2-pulses into controls (Y, Z, and X pi/2-pulses, and then the same sequence but with negative rotation angles). This test currently fails in the master branch.
To solve the problem, I took two things into account:
1. As the value of the detuning angle can be negative, when we calculate the duration of a Z pulse, we have to use the absolute value of the detuning angle.
2. When the detuning angle is negative, the detuning rate used to generate the controls should also be negative.
With these two fixes, the tests pass.

Adding support to convert DDS with pi/2-pulses into controls

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
tests/test_dynamical_decoupling.py

I added tests for the conversion of DDS to DrivenControls of sequences containing pi/2-pulses at the beginning and end of their duration. The test for Y pi/2-pulses currently fails in the master branch.
The reason for this are two lines of code that skip the creation of a pulse if (offset + rabi angle + azimuthal angle + detuning angle) is zero. This is the case for a Y (-pi/2)-pulse at the beginning of the DDS: 0 + pi/2 + (-pi/2) + 0 = 0.
Removing those lines didn't seem to cause any new problem: all tests continue passing, including the  ones that check the conversion of a free evolution.

Fixing conversion of a Y pi/2-pulse at the beginning of a DDS

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
tests/test_dynamical_decoupling.py

Partially fixes
https://q-ctrl.atlassian.net/browse/QENG-714
and was sparked by the discussion in 
https://github.com/qctrl/python-core/pull/322
I added an optional `minimum_segment_duration` to the DDS -> DrivenControls converter. The idea is: if the pulse duration estimated from the maximum frequency is smaller than the minimum segment value selected, then the `minimum_segment_duration` is used instead. The amplitudes of the controls are then calculated from the total rotation we want to achieve and the duration of the pulse, rather than always taking the maximum possible value.
I was maybe a bit conservative in these changes, and didn't touch other aspects of this function, such as the requirement that no pulse can simultaneously have Rabi and detuning rotations (alhtough I added a …

[QENG-714] Adding a minimum_segment_duration to DDS to controls converter

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py

This is the first step towards simplifying and making the argument check mentioned in the following comment more floating-point friendly:
https://github.com/qctrl/python-open-controls/pull/67#discussion_r400668817
in order to solve Luigi's bug.
This PR eliminates the need of checking whether all the pulse starts are smaller or equal to the pulse ends, by making sure that all the `half_pulse_duration` are positive. This is done in two parts:
1. Making sure we take the absolute value of the Rabi rotation when calculating the `half_pulse_duration`. In principle this should be a positive value, but lacking any prior test there might be nothing stopping the user to try to set it as -pi/2 as a way to obtain a (-pi/2)-pulse in the X direction, for example. (The proper way to do that would be to …

Making sure all half_pulse_durations are positive

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
tests/test_dynamical_decoupling.py

Final part of the fix for the bug found by Luigi. First part was PR #68
I split the checks of the timing of the pulses into two parts:
1. Checking that all the offsets are in ascending order in time (and adding the information about this requirement to the docstring).
2. Checking that none of the pulses overlap.
These two checks should be tolerant of floating point imprecisions now.
I added a unit test that replicates exactly the situation that Luigi reported. In the master branch, this test fails with the exception:
```
ArgumentsValueError: Pulse timing could not be properly deduced from the sequence operation offsets. Try increasing the maximum rabi rate or maximum detuning rate.
```

Making the errors in DDS to Controls conversion more floating-point-friendly

---

tests/test_predefined_dynamical_decoupling.py

Ran into this typo while looking for something unrelated. As this is an open repository, it might be worth fixing even typos in comments

Fixing typo in comments of a test

---

.github/workflows/on-push.yml
setup.py

The markdownlint check here is unenforced, due to the `|| true` after it. It would make sense to either remove the `|| true` to enforce the checks, or to simply remove the check altogether. The preference among the quantum product engineering team seems to be to remove the check

Remove unenforced markdownlint check from push workflow

---

qctrlopencontrols/driven_controls/driven_control.py
tests/test_driven_controls.py

Currently, running
```
from qctrlopencontrols import DrivenControl
control = DrivenControl(rabi_rates=[1, 0, 1], detunings=[0, 0, 0], durations=[1, 1, 1])
control.directions
```
will result in an error, because the segment with zero amplitude (the second segment) will cause a division by zero in the `directions` method. This patch prevents that division by zero.
Let me know if you'd prefer a different solution

Fixing bug in DrivenControl.directions method

---

matplotlibrc

It seems `matplotlibrc` is used for customized style in the plot
https://matplotlib.org/3.2.2/tutorials/introductory/customizing.html,
but not really been used in the repo.

Remove unused file

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
tests/test_predefined_dynamical_decoupling.py

As discussed in https://q-ctrl.atlassian.net/browse/QENG-974
we now add x rotations unconditionally to all DDS, but the sign of the post-rotation could be different depending on the control scheme. The net effect of DDS now does not have to be identity, this is captured in tests.
I have a strange test error. All tests pass on local machines (tested on Mac and Linux). However, there seem random failures in CI. The issue is related to the function `test_if_quadratic_sequence_with_odd_inner_pulses_is_identity` in ` tests/test_predefined_dynamical_decoupling.py`. See commit `75e3a6c` for example. I notice sometimes rerun the action would resolve the issue, but I don't have a clue why it happens. @leoadec @charmasaur

Fix pre-post rotations

---

qctrlopencontrols/utils.py

While adding `mypy` to check type, it seems some refactor for argument checking is necessary besides just adding type hints. It will be easier to add this check function first.
We might apply this function for all arguments check in the future. 
This is also part of the issue https://github.com/qctrl/python-open-controls/issues/90#issue-653672409

Add a function to check arguments

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

Note that type hints are not added for functions like `new_**` as we will refactor them soon (see https://github.com/qctrl/python-open-controls/issues/93).

Add type hints for some functions in DDS module

---

qctrlopencontrols/driven_controls/predefined.py

Private methods like `_new_***` allow `rabi_rotation` to be optional but they all call `_predefined_common_attributes` which does not allow `rabi_rotation` to be `None`.
Some refactoring is done to make sure the code pass type checking.
Edit: note that this is only to fix the type issue, but does not fix the bug when user doesn't explicitly set `rabi_rotation`.

Add type hint for predefined driven control

---

qctrlopencontrols/driven_controls/driven_control.py
tests/test_driven_controls.py

Add type hint
For passing `mypy` test, some refactoring is done for checking the inputs. The main purposes of these checking are:
1. set proper default values when inputs are all ``None``
2. make sure all non ``None`` inputs have the same shape
3. set the proper values for ``None`` input
Note that type hint is not added for those properties as I am planning to rearrange those checkings first. Will do in another PR.

Add type hint for drive control module

---

qctrlopencontrols/driven_controls/predefined.py
tests/test_predefined_driven_controls.py

This function should be the same as the one in core with some tweaks. We expect users to use it to generate amplitude noise characterization pulses.
Tests are migrated and modified a bit.

Add function to generate modulated Gaussian control

---

qctrlopencontrols/__init__.py

Expose new_modulated_gaussian_control

---

qctrlopencontrols/driven_controls/predefined.py

For the private function names I've opted to make them consistent with
the scheme names, since those are presumably the most natural ways to
refer to them.
Plan is to make the private functions public, and document those
functions with full details. Eventually we can probably delete the
new_predefined_driven_control, although it's fine to stick around for a
while for compatibility purposes.
https://q-ctrl.atlassian.net/browse/QENG-1118

Fix scheme names and make private function names consistent

---

qctrlopencontrols/driven_controls/driven_control.py

The amplitudes and Rabi rates are supposed to be given in proportion to
the maximum Rabi rate:
https://docs.q-ctrl.com/wiki/output-data-formats#q-ctrl-hardware
Also just use the azimuthal angles directly, rather than taking an arctan of
the amplitudes.
https://q-ctrl.atlassian.net/browse/QENG-1118

Fix scaling of amplitudes when exporting controls

---

qctrlopencontrols/driven_controls/predefined.py

This covers the [single qubit driven control library](https://docs.q-ctrl.com/wiki/control-library) section of the wiki.
Changes are largely based on the wiki, although some of the references
have been fixed, and the description of WAMF1 now more accurately
matches the code.
The styling of the tables isn't great, but I'm hoping that's something that
can be fixed separately on the frontend side.
In a subsequent PR I'll make all these functions public, to be used instead
of `new_predefined_driven_control`.
Preview: https://qeng-1118.docs.q-ctrl.com/references/python/qctrl-open-controls/qctrlopencontrols.html
(for that preview I've made the functions public, but you get the idea)
https://q-ctrl.atlassian.net/browse/QENG-1118

Expand documentation for predefined driven controls

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

- some name tweak
- fix typo
I guess spin echo is fine? (although in the doc we do call it `se`)

 Use abbreviation in predefined DD functions

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

This PR moves the doc from wiki to the dynamical decoupling module.
Most of the content would be the same as shown in https://docs.q-ctrl.com/wiki/control-library,
except for the doc of the Walsh sequence, where I added a bit more details from the internal document.
You may find some of the default values do not make much sense. I have a plan to fix this later.
This PR would mainly just migrate the doc.
Preview:
https://product-2318.docs.q-ctrl.com/references/python/qctrl-open-controls/qctrlopencontrols.html

[Product 2318] Add doc to dynamical decoupling module

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

Note that `number_of_offsets = int(number_of_offsets)` was in the main function before and moved to private functions during the refactor. However, the best practice is to do it close to the input as discussed in #130.
This PR puts the cast back to where it was.

number_of_offsets type cast

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_dynamical_decoupling.py

This PR mainly focuses on the value-checking of `DynamicDecouplingSequence`.
`duration` and `offsets` are now not optional as I can't find a good reason/way to do it. Note that:
1.  following inputs, like `rabi_rotations`, depend on `offsets` if they are not provided.
2.  use 1 and [0.5] as default values for `duration` and `offsets` just feel wrong.
3. I think they were there because of the old design of Black Opal. Functions in this repo are obsessed to have default values all the time.
If you agree with this change, I would propose to also make duration as non-optional input for functions in the predefined module.
`number_of_offsets` is also removed as it was used for value checking.

Refactor `DynamicDecouplingSequence`

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

Part of me still wants to remove the `name` parameter as that might be there for BLACK OPAL.
That would require removing them in all driven control functions and DDS function.

Remove unnecessary default values in DDS functions

---

examples/creating-a-dynamical-decoupling-sequence.ipynb
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
tests/test_predefined_dynamical_decoupling.py

`number_of_offsets` -> `offset_count`
`number_inner_offsets` -> `inner_offset_count`
`number_outer_offsets` -> `outer_offset_count`
This is a breaking change. We might do a release later after removing the drive control wrapper function.
Also removed unnecessary default values in private functions.

Change varibale name using Q-CTRL standard

---

qctrlopencontrols/driven_controls/predefined.py

This is the first PR of another series of PRs for refactoring the driven control module, which will include:
- remove the wrapper function `new_predefined_driven_control`
- remove unnecessary inputs, if any
- remove unnecessary default values
- use check function rather than raising errors
- format tweak, if necessary
As the first step, this PR refactors a private checking function shared by some predefined driven control functions. The `float` type cast is removed and now it would only do the checking, but not returning any value. The name is also tweaked, to better reflect its funciotinality.

Refactor a parameter-checking function for predefined driven-control functions

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_dynamical_decoupling.py

Remove unnecessary default values for the DDS class.
Also, remove the check for the number of offsets exceeds `UPPER_BOUND_OFFSETS` as I think this was for BLACK OPAL.
I think we can turn DDS into a dataclass and just remove the `__repr__` and `__str__`, which seem quite unnecessary here.

Remove default values of DDS

---

qctrlopencontrols/driven_controls/driven_control.py

Fix an error made in #86, where `CARTESIAN` is mistakenly replaced by `CYLINDRICAL`.

Fix an error in export format

---

qctrlopencontrols/driven_controls/driven_control.py

This PR proposes to remove `bound constraints` defined in https://github.com/qctrl/python-open-controls/blob/master/qctrlopencontrols/constants.py
These values don't have particular physical meaning, but might be for the consideration of Black Opal. Since we don't have this constrain now, it might be good to remove these bounds and let user decide what to do with bounds depnding on the limitations of their apparatus.
The draft PR only removes the constraints in `DrivenControl` class. Would remove them from the whole repo if you think this is a sensible proposal.

Remove bound constraints on driven control

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_dynamical_decoupling.py

- remove unnecessary default values in convert_dds_to_driven_control
- refactor the checking function a bit
-  change default value of `minimum_segment_duration` to `None`. If it's `None`, set it to 0 in the code such that we don't change the behaviour of this function

Remove default values in `convert_dds_to_driven_control`

---

qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
tests/test_driven_controls.py

- remove unnecessary default values in `DrivenControl`
- modify tests depending on the default values
- add `detunings` to `new_modulated_gaussian_control` as defaults values  are now removed.

Remove default values in DrivenControl

---

tests/test_driven_controls.py
tests/test_dynamical_decoupling.py
tests/test_predefined_dynamical_decoupling.py

In preparing of enabling the `check_untyped_defs` option, we first fix the type in issue in the test.
The type issues are mainly due to the casting among List, string, and numpy.ndarray.

misc: Fix type issue in tests

---

qctrlopencontrols/driven_controls/predefined.py

- remove the default value for maximum_rabi_rate
- minor tweak for parameter checking

 misc: Remove default value  in `new_corpse_in_scrofulous_control`

---

qctrlopencontrols/driven_controls/predefined.py
tests/test_predefined_driven_controls.py

Should be the last one of the `default-value` series.
Thanks @charmasaur !

misc: Remove default value in `new_wamf1_control`

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

There is no need to have default values in private functions and these are probably missed from earlier PRs.
Minor tweak to the doc.

misc: Remove default values in private function

---

README.md

Adding a note to the README about how to use pre-push instead of pre-commit (and how to uninstall it).

misc: Add information about pre-push

---

.gitignore
docs/Makefile
pyproject.toml
qctrlopencontrols/__init__.py
setup.py

This is necessary due to a sphinx bug
(https://github.com/sphinx-doc/sphinx/issues/1999), but until
that's fixed we might as well have a `make clean` implementation
that actually cleans.

fix: Remove auto-generated docs files with make clean

---

README.md

The naming conventions in Elements (https://elements.q-ctrl.com/code/naming-conventions/#projects) say that:
1. The project name is what you see as the main heading in the README file of the repository.
2. The name of this project is  Q-CTRL Python Open Controls.
As this README has a different heading, I'm changing it to be the project name "Q-CTRL Python Open Controls".
- Change header of the README to "Q-CTRL Python Open Controls".

fix: Fix project name in the README

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_dynamical_decoupling.py

- Enforce non-negativity of Rabi rotations during creation of a `DynamicDecouplingSequence` object

feat: Enforce non-negativity of Rabi rotations

---

pyproject.toml
setup.py

According to https://github.com/qctrl/template/blob/master/pyproject.toml#L18 the `description` field in `pyproject.toml` has to be the project name ("Q-CTRL Python Open Controls") rather than the package name ("Q-CTRL Open Controls").
- Change the description field in `pyproject.toml` to match the project name.
- Change the description field in `setup.py` to match the project name.

misc: Fix description field in pyproject.toml

---

poetry.lock
pyproject.toml
setup.py

Using `grep`, I couldn't find any use of `scipy` in the repo, so I think we can remove it from the dependencies.
- Remove `scipy` from dependencies in `pyproject.toml`, `poetry.lock`, and `setup.py`.

fix: Remove scipy from dependencies

---

.github/workflows/on-push.yml
poetry.lock
pyproject.toml
setup.py

I tried locally in my computer, and this seems to run fine in Python 3.9, so I don't think we need to restrict our users to older versions of Python.
- Lift restriction that Open Controls is only compatible with Python < 3.9
- Add unit tests for Python 3.9 in the CI.
- Update name of the docker images in the CI.

feat: Make Open Controls compatible with Python 3.9

---

pyproject.toml

The "housekeeping" workflow from the CI will automatically update `setup.py`, so it's no longer necessary to advise users to install and run `dephell`, a package that has been discontinued (https://github.com/dephell/dephell/#the-project-is-archived) and which is not compatible with the latest versions of `pip` (https://github.com/dephell/dephell/blob/master/pyproject.toml#L151).
- Update pyproject.toml comment to no longer recommend running dephell.

misc: Update pyproject.toml comment to avoid dephell

---

poetry.lock
pyproject.toml

Related to: https://q-ctrl.atlassian.net/browse/PRODUCT-2501
This package currently can't be directly installed in editable with `pip install -e .` because `setuptools` is missing from the requirements. This also bumps the poetry version required to a stable one.
- Fix the`build-system` in the file `pyproject.toml`.
- Update poetry.lock.

fix: Allow package to be installed in editable mode

---

.github/workflows/on-push.yml
.github/workflows/on-release.yml

Addresses: https://q-ctrl.atlassian.net/browse/DEVOPS-885
- Add wait for deployments
- Deploy to AWS Production cluster

feat: Deploy to AWS Production Cluster

---

examples/creating-a-driven-control.ipynb
examples/creating-a-dynamical-decoupling-sequence.ipynb

Addresses: https://q-ctrl.atlassian.net/browse/(ticket)
Resolves #197.
- Fixes broken links in example notebooks.
- Address broken links in the section titled 'Opening the exported sequence in Q-CTRL BLACK OPAL' of [creating-a-dynamical-decoupling-sequence.ipynb](https://github.com/qctrl/python-open-controls/blob/291bb40e19042739f4fdcf1a3065a20c40b80ef9/examples/creating-a-dynamical-decoupling-sequence.ipynb).

Bugfix broken links

---

examples/creating-a-driven-control.ipynb
examples/creating-a-dynamical-decoupling-sequence.ipynb

fix: Remove references to deprecated BLACK OPAL

---

qctrlopencontrols/driven_controls/driven_control.py
tests/test_driven_controls.py

Alternative to https://github.com/qctrl/python-open-controls/pull/200. Even though this one is a bit less consistent with BOULDER OPAL, I think it's better. For a start, it means the user can also benefit from resampling for the export-to-file function too, which I would have thought should be very useful. Also, I don't think consistency with BOULDER OPAL is that important here, because DrivenControl is a very different beast to a plain old pulse.

feat: Add function to resample a driven control

---

.github/workflows/on-pull-request.yml

It seems I forgot to remove python 3.6 from the on-pull-request workflow and causing an issue in #209 .

misc: Remove Python3.6 from on-PR workflow

---

.github/workflows/on-pull-request.yml
.github/workflows/on-push.yml
.github/workflows/on-release.yml

Some workflows like https://github.com/qctrl/python-open-controls/runs/4553896326 seem to be failing due to out-of-date image names. This should update the pattern of the image names from `python-build:3.7` to `ci-images:python-3.7-ci` throughout the workflows.
- Update the name of the Docker images in the CI.

misc: Update Docker image names

---

qctrlopencontrols/driven_controls/predefined.py

The expressions for the CORPSE angle $\theta^3$ in the doc strings of `new_corpse_control`, and the three methods `new_corpse_in_*_control`, were missing a $\sin^{-1}$. This PR adds the sin^{-1} in four places. The code itself looks correct.

fix: Fix doc typos in driven_controls/predefined.py

---

poetry.lock

Basically a copy of this dependabot PR: https://github.com/qctrl/python-open-controls/pull/214
Just updating the version of pillow in the `poetry.lock` file.
- Update version of `pillow` in the `poetry.lock` file.

fix: Update pillow

---

.github/workflows/check-pr-format.yml
.github/workflows/on-pull-request.yml
.github/workflows/on-push.yml
.github/workflows/on-release.yml
poetry.lock

A suggested in https://github.com/qctrl/python-qiskit/issues/25 , this updates `actions/checkout@v1` to `actions/checkout@v2` in the GitHub Actions workflows.
- Update `actions/checkout@v1` to `actions/checkout@v2`.

fix: Update version of actions checkout

---

qctrlopencontrols/constants.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
tests/test_driven_controls.py
tests/test_dynamical_decoupling.py
tests/test_predefined_dynamical_decoupling.py

To prepare upgrading to NumPy 1.20+, this PR fixes the type issue as type hint can work with most of the NumPy objects (instead of being `Any` before).

fix: Fix type issue with NumPy

---

poetry.lock
pyproject.toml
setup.py

Update NumPy to 1.20+ (see also  #216).
BREAKING CHANGE:
Users/developers need to upgrade NumPy to 1.20+.

feat!: Update NumPy version

---

poetry.lock
pyproject.toml
qctrlopencontrols/__init__.py
setup.py

To address #221. `ipython` is used by `nbval`. It seems `ipython` has dropped support of Python 3.6 since `7.17` ( see [here](https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#ipython-7-17)).
We might just update to 7.31.1 (the latest `7.X` version and `8.X` is still in alpha/beta stage).
- update `ipython` to 7.31.1

misc: Update ipython version to 7.31.1

---

.github/README.md

- Add information in the README about how to find the reference documentation hosted online.

misc: Add link in the README to the hosted reference docs

---

qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

- Uses positive instead of greater than zero in error messages if value > 0
- Uses non-negative in error messages instead of greater than zero in error messages if value >= 0

misc: Use positive in error messages

---

examples/creating-a-driven-control.ipynb
examples/creating-a-dynamical-decoupling-sequence.ipynb
poetry.lock
pyproject.toml

This simplifies the dependencies, and also allows us to support python 3.11 later.
Add a comment about installing qctrl-visualizer. Note that since visualizer was a dev-dependency, users need to install it first anyway.

build: Remove qctrl-visualizer from dev-dependencies

---

.github/workflows/on-push.yml
poetry.lock
pyproject.toml

- Specify NumPy based on Python versions
- Update mypy to the latest version to pick up a bug [fix](https://github.com/python/mypy/issues/13627)
- Use the same dependencies for doc building as in Boulder Opal (we can bump them together once the theme issue is resolved).
- Use Python 3.11 in CI

build: Support Python 3.11

---

docs/Dockerfile
poetry.lock
pyproject.toml

- Regenerate lock file with poetry 1.2.2
- Update image for doc
- Remove nbval as we are not using it in the CI (we already removed visualizer)

build: Regenerate lock file

---

docs/conf.py

- Add Oxford comma to the description of the package in the Sphinx documentation, as per the Microsoft Style Guide.

style: Add Oxford comma to description of the package

---

.github/workflows/on-release.yaml

We only need one vault login in the workflow to publish the documentation.
This pull request removes the duplicate vault login for the python-open-controls CI.
- Remove duplicate vault login in the CI workflow that publishes reference documentation.

ci: Remove duplicate vault login

---

docs/_templates/qctrlopencontrols/qctrlopencontrols.rst
docs/index.rst

Use the [package name](https://code.q-ctrl.com/naming-conventions#packages) in the reference documentation, as specified in the [documentation guidelines](https://code.q-ctrl.com/documentation#user-documentation).
- Use the package name (Open Controls) in the title of the user reference documentation.

docs: Use package name in the documentation

---

pyproject.toml

The URL `https://poetry.eustace.io/docs/versions` sends you to a 404 error, so it might be best to remove it from pyproject.toml.
This comment is present in many repos, so I've attempted to use Microplane to make it easier to deploy the changes everywhere.
- Remove broken link to `https://poetry.eustace.io/docs/versions` from `pyproject.toml`.

ci: Remove broken poetry URL in pyproject.toml

---

qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_dynamical_decoupling.py

- Fix capitalization of Rabi and spelling of coordinate.
- Remove mention of BLACK OPAL.
- Improve consistency of export method docstrings.

docs: Fix small issues in docstrings

---

docs/conf.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

See context in https://github.com/qctrl/python-visualizer/pull/266
Also fix a link in the doc.

build: Do not show type hint in the signature

---

docs/conf.py

- Update the segment key used in the reference docs to the prod one, so that Intercom will stop using the "Q-CTRL Test" environment.

docs: Update segment write key to use the prod environment

---

.github/README.md
.github/workflows/on-pull-request.yaml
.github/workflows/on-push.yaml
.github/workflows/on-release.yaml
.pylintrc
poetry.lock
pyproject.toml

To fix possible security issue and python 3.7 is near its EOL.

build!: Drop support of python 3.7

---

poetry.lock
pyproject.toml

To remove dependency of `toml`.

chore: Bump qctrl-sphinx-theme

---

.github/workflows/on-release.yaml
docs/Dockerfile
docs/conf.py

Fetch the `SEGMENT_WRITE_KEY` from the Vault, instead of using a hard-coded value.
The `SEGMENT_WRITE_KEY` isn't a "real" secret (anybody can see it by looking at the source code of the reference documentation on their browsers), but if it's retrieved from a central place at least we won't have to update it in all the repos if it changes in the future. It will be sufficient to update it in the Vault.
- Retrieve `SEGMENT_WRITE_KEY` from the Vault.

docs: Fetch segment write key from the Vault

---

docs/Dockerfile

NOTE: Needs to have ci-image change merged in before merging so image is built/pushed
Addresses: https://qctrl.atlassian.net/browse/PR-120
- Change to Q-CTRL nginx image to allow for large headers in requests.
For context: https://github.com/qctrl/ci-images/pull/193

ci: Change to qctrl nginx image to allow large headers

---

.github/README.md
docs/installation.rst

- Update repo name from `python-open-controls` to `open-controls` in the README and reference documentation.

docs: Update repo name in readme and docs

---

.github/README.md
pyproject.toml

A few things I missed #274 . Mainly, that without "python" in the name of the repo, the project name should now be "Q-CTRL Open Controls" rather than "Q-CTRL Python Open Controls".
- Update project name to "Q-CTRL Open Controls".
- Update repo name in `pyproject.toml`.

chore: Update project name

---

docs/conf.py

There's some legacy code in the file `docs/conf.py` that is no longer necessary to build the reference docs.
As can be seen from the code comment, these were variables to be inserted in the file `_templates/layout.html`, which is no longer present in this repo.
(I removed that file as part of #254, but didn't realize that the new `_templates/layout.html` file from the Q-CTRL Sphinx Theme doesn't need any of those variables.)
- Remove legacy code from `docs/conf.py`.

build: Remove legacy code from docs/conf.py

---

.github/README.md
.pre-commit-config.yaml
.prettierrc
README.md

- Bump `pre-commit-hooks` to the latest version.
- Add `prettier` to the pre-commit hooks.
- Add a `.prettierrc` configuration file.
- Rerun `pre-commit` to reformat Markdown files with the agreed upon style.

style: Bump version of pre-commit-hooks and add prettier

---

docs/conf.py
poetry.lock
pyproject.toml

The security issue from `certifi` is supposed to be fixed in #279, but the alarm is still there. Could be a bug of Dependabot itself.
We just take this chance to bump all dev tools and clean up `pyproject.toml`.

build: Bump dev tools

---

.github/workflows/on-release.yaml

Addresses: https://qctrl.atlassian.net/browse/ACC-562
- Remove docs update step on release

ci: Remove docs update step on release

---

.github/workflows/on-release.yaml
poetry.lock
pyproject.toml

Addresses: https://qctrl.atlassian.net/browse/ACC-653
- Update markdown builder package version

build: Update markdown builder package version

---

qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

Addresses: https://qctrl.atlassian.net/browse/PA-2317
This pull request includes several changes to the `qctrlopencontrols` library, specifically within the `driven_controls` and `dynamic_decoupling_sequences` modules. The primary focus of these changes is to standardize the notation for the maximum Rabi frequency and improve the clarity of mathematical expressions.
Standardization of notation:
* Updated the notation for the maximum Rabi frequency from `\Omega_{\rm max}` to `\Omega_{\mathrm max}` in the `new_primitive_control`, `new_bb1_control`, `new_sk1_control`, `new_scrofulous_control`, `new_corpse_control`, `new_corpse_in_bb1_control`, `new_corpse_in_sk1_control`, `new_corpse_in_scrofulous_control`, and `new_wamf1_control` functions. …

fix: Update mathematical notation for consistency in predefined.py

---

.github/workflows/on-pull-request.yaml

Updated CI workflow to use the latest pre-check on-pull-request resuseable workflow for checking internal versions.
This ensures consistency, improves automation, and makes it easier to manage any future changes.
Addresses: https://qctrl.atlassian.net/browse/INFRA-2128

ci: Add new on-pull-request workflow

---

.github/workflows/on-pull-request.yaml

Update the docker build ci workflow which now uses the installed `docker
build` command on the workflow runner.
This job only builds an image so there is no need to add a tag with the
suffix `-docs` this is mainly for testing the docker build runs without
any issues.

ci: Add docker build push docker workflow

---

.github/workflows/on-pull-request.yaml
.github/workflows/on-push.yaml
.github/workflows/on-release.yaml

This change removes the `ci docker run ...` commands and uses the `container:` image name in the job instead, also please note that this repository is public and we cannot use our private org reusable workflows here due to restriction on private org reusable workflow repositories.

ci: Remove docker run commands and use container images in jobs instead
