.gitignore
.readthedocs.yml
README.md
README.rst
docs/Makefile
docs/_static/css/custom.css
docs/_templates/breadcrumbs.html
docs/conf.py
docs/index.rst
docs/licence.rst
docs/matplotlibrc
docs/qctrlopencontrols.base.rst
docs/qctrlopencontrols.cirq.rst
docs/qctrlopencontrols.driven_controls.rst
docs/qctrlopencontrols.dynamic_decoupling_sequences.rst
docs/qctrlopencontrols.exceptions.rst
docs/qctrlopencontrols.globals.rst
docs/qctrlopencontrols.pyquil.rst
docs/qctrlopencontrols.qiskit.rst
docs/qctrlopencontrols.rst
poetry.lock
pyproject.toml
setup.py

Preview link: https://qctrl-python-open-controls.readthedocs-hosted.com/_/sharing/chhr71t4cloz10apwx9qrke29
I'm getting a few docstring parse errors even though numpy docstring parsing is enabled. I would imagine these can be cleaned up progressively however.
```
/Users/steve/Source/Quantum Engineering/python-open-controls/qctrlopencontrols/__init__.py:docstring of qctrlopencontrols.convert_dds_to_qiskit_quantum_circuit:6: WARNING: Unexpected indentation.
/Users/steve/Source/Quantum Engineering/python-open-controls/qctrlopencontrols/__init__.py:docstring of qctrlopencontrols.convert_dds_to_qiskit_quantum_circuit:7: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/steve/Source/Quantum Engineering/python-open-controls/qctrlopencontrols/driven_controls/driven_contro …
```

Documentation generation

---

.github/workflows/on-push.yml
poetry.lock
pyproject.toml
setup.py

Also run CI against 3.8.
https://q-ctrl.atlassian.net/browse/QENG-630

Declare python 3.8 support

---

docs/conf.py

Add styling

---

docs/_templates/layout.html

Add analytics script

---

README.md
README.rst
docs/index.rst
docs/installation.rst
qctrlopencontrols/__init__.py

Specifically:
- fix some typos in the README and installation instructions
- update the top-level package docstring to be more consistent with the
visualizer
- include a summary sentence in the docs index
https://q-ctrl.atlassian.net/browse/QENG-678

Improve docs and README

---

LICENSE
qctrlopencontrols/__init__.py
qctrlopencontrols/base/__init__.py
qctrlopencontrols/base/utils.py
qctrlopencontrols/driven_controls/__init__.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/__init__.py
qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
qctrlopencontrols/exceptions/__init__.py
qctrlopencontrols/exceptions/exceptions.py
qctrlopencontrols/globals/__init__.py
tests/__init__.py
tests/test_driven_controls.py
tests/test_dynamical_decoupling.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

Replace Q-CTRL terms of service with Apache 2.0 license.

Updated license

---

qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

Just a few typos I encountered during the last task.
I wonder if it might be worth running a spell checker of some kind before in a public repo like this one. Maybe it's possible to set one up like we do with pylint.

Miscellaneous typo corrections

---

README.md
README.rst
examples/creating-a-driven-control.ipynb
examples/creating-a-dynamical-decoupling-sequence.ipynb
poetry.lock
pyproject.toml
setup.py

https://q-ctrl.atlassian.net/browse/QENG-802
#70

Add example notebooks

---

docs/Dockerfile
docs/_templates/layout.html
docs/conf.py

* Bump nginx image to 1.18
* Reference central Segment analytics script
* Update copyright to match https://docs.q-ctrl.com
* Remove development environment references

Various Sphinx updates

---

examples/creating-a-driven-control.ipynb
examples/creating-a-dynamical-decoupling-sequence.ipynb
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py

Fixes PRODUCT-1802
Update broken links to documentation.

Update broken links

---

poetry.lock
pyproject.toml
setup.py

Switch sphinx-rtd-theme to be a dev dependency

---

docs/matplotlibrc

Remove unused file

---

docs/conf.py
poetry.lock
pyproject.toml
qctrlopencontrols/__init__.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
setup.py
tests/test_dynamical_decoupling.py

Apply isort

---

.github/workflows/on-push.yml
mypy.ini
poetry.lock
pyproject.toml
setup.py

Note this doesn't really check any function for now as we haven't added type hint yet.
The plan is to add type hints for all existing functions in the future.

Add `mypy` to dependencies and CI

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py

Add type hint to `convert_dds_to_driven_control`

---

qctrlopencontrols/driven_controls/__init__.py

Just a small fix for a typo that's been around since the beginning of time

Fixing CORPSE typo

---

qctrlopencontrols/driven_controls/driven_control.py

The input checkings were done with properties, which should be done before the field values are set.

Rearrange input checking for driven control module

---

qctrlopencontrols/constants.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
qctrlopencontrols/utils.py
tests/test_driven_controls.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

Put all constants in a single file and change import accordingly.

Add constants file

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py

import constant from `constants.py`.
This should be done in the previous PR. It was missed.

Fix import

---

qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

https://q-ctrl.atlassian.net/browse/QENG-1118

Tweak docs for consistency and valid reST

---

.github/workflows/on-push.yml
poetry.lock
pyproject.toml
qctrlopencontrols/exceptions.py
setup.py

Uses the profile option from isort to keep the style consistent with black

Set isort profile black

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

This is part of https://q-ctrl.atlassian.net/browse/PRODUCT-2318, so we can easily check changes in doc.

Make predefined DD functions public

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

We will apply the same pattern for other DDS functions. That is,
1. remove all `ArgumentsValueError` by using `check_arguments` function
2. remove all `kwargs`
3. fix default values
`_check_duration` will be removed after we finish refactoring all DDS functions.

Refactor `new_ramsey_sequence`

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

Refactor `new_cpmg_sequence`

---

qctrlopencontrols/dynamic_decoupling_sequences/predefined.py

The implementation needs lots of rework, but that would be another PR(s) in future.

Fix default values in `new_xy_concatenated_sequence`

---

qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py

This is to prepare the refactor of `convert_dds_to_driven_control`

Use check function to raise error

---

docs/Dockerfile
docs/conf.py

Fixes # .
- Change 1
- Change 2
- Change 3

Modify copyright message, add dynamic year. Upgrade nginx to 1.19.

---

poetry.lock
pyproject.toml
setup.py

- update sphinx version
- also update `qctrl-visualizer` version (note this didn't break anything, there is no harm in updating it anyway)

Update sphinx and qctrl-visualizer version

---

.gitignore

ignore the intermediates files while generating doc locally

Update .gitignore files

---

qctrlopencontrols/constants.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
tests/test_driven_controls.py

As discussed in #153, we now remove all constant bounds in this repo.

Remove bounds of controls

---

qctrlopencontrols/driven_controls/predefined.py

- remove default value of `maximum_rabi_rate` in `new_sk1_control`
- minor doc tweak in `new_primitive_control` and `new_bb1_control`

misc: Remove default values in `new_sk1_control`

---

qctrlopencontrols/driven_controls/predefined.py

Remove default values in `new_corpse_control`, `new_corpse_in_bb1_control`, and `new_corpse_in_sk1_control`

misc: Remove default values

---

qctrlopencontrols/driven_controls/driven_control.py

Some minor math fixes in the comment string.

fix: Documentation string math

---

.github/workflows/check-pr-format.yml
.github/workflows/on-pull-request.yml
.gitlint

To ensure we have consistent PR names as discussed in #179

misc: Add check for PR names

---

README.md

fix: Update out-of-date readthedocs information

---

qctrlopencontrols/__init__.py
qctrlopencontrols/constants.py
qctrlopencontrols/driven_controls/__init__.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/__init__.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
qctrlopencontrols/exceptions.py
qctrlopencontrols/utils.py
tests/test_driven_controls.py
tests/test_dynamical_decoupling.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

Update format of the license according to: https://elements.q-ctrl.com/code/licensing/#applying-the-open-source-license-in-python
- Update license in the header of the Python files.

misc: Update license in the header of the Python files

---

.github/README.md

Use correct path to license in README

fix: Fix path in README

---

docs/conf.py
qctrlopencontrols/__init__.py
qctrlopencontrols/constants.py
qctrlopencontrols/driven_controls/__init__.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/__init__.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
qctrlopencontrols/exceptions.py
qctrlopencontrols/utils.py
tests/test_driven_controls.py
tests/test_dynamical_decoupling.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

Update license. 
We also change the license for `docs/conf.py` from the Q-CTRL one to the Apache one.

misc: Update license

---

qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

Remove unnecessary comma for `black`.

misc: Fix code format

---

docs/conf.py

This PR was generated automatically by the `licensing.sh` script in
https://github.com/qctrl/repositories-manager
If anything is wrong with this PR, please check the PRs on the `repositories-manager`
repo. If there's no PR open that causes the change, please create a new one.

misc: Update licensing comments

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

misc: Update version of lint tools

---

.github/workflows/on-release.yml

@cfarrend, I am about to do a release for open control and  thinking this might be the chance that we can test whether this would fix the V2 issue. If not, I guess we could downgrade to V1 in other repos.
See related  issues:
https://github.com/actions/checkout/issues/217
https://github.com/actions/checkout/issues/290

misc: Tweak release CI

---

qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
qctrlopencontrols/utils.py

Changes in this PR:
- Apply the PEP standard as discussed.
- Add missing type hint.
- Minor tweaks to some docs.

style: Apply PEP 585/604 for type annotations

---

poetry.lock

build: Bump versions

---

.github/README.md

We have supported 3.11 in #241.

docs: Update readme

---

pyproject.toml

Follow up to https://github.com/qctrl/template/pull/20
- Update list of keywords in `pyproject.toml` to match the one in the [template repo](https://github.com/qctrl/template/blob/master/pyproject.toml).

chore: Update list of project keywords

---

docs/conf.py
qctrlopencontrols/__init__.py
qctrlopencontrols/constants.py
qctrlopencontrols/driven_controls/__init__.py
qctrlopencontrols/driven_controls/driven_control.py
qctrlopencontrols/driven_controls/predefined.py
qctrlopencontrols/dynamic_decoupling_sequences/__init__.py
qctrlopencontrols/dynamic_decoupling_sequences/dynamic_decoupling_sequence.py
qctrlopencontrols/dynamic_decoupling_sequences/predefined.py
qctrlopencontrols/exceptions.py
qctrlopencontrols/utils.py
tests/test_driven_controls.py
tests/test_dynamical_decoupling.py
tests/test_predefined_driven_controls.py
tests/test_predefined_dynamical_decoupling.py

This PR was generated automatically by the `licensing.sh` script in
https://github.com/qctrl/repositories-manager
If anything is wrong with this PR, please check the PRs on the `repositories-manager`
repo. If there's no PR open that causes the change, please create a new one.

chore: Update licensing comments

---

.github/workflows/on-push.yaml
docs/conf.py
poetry.lock
pyproject.toml

- Bump version of the Q-CTRL Sphinx Theme.

docs: Fix search feature

---

.github/workflows/on-push.yaml

Addresses: https://qctrl.atlassian.net/jira/software/projects/DEVOPS/boards/16?selectedIssue=DEVOPS-1051
Changes proposed:
- Update workflow to deploy to new dev cluster

build: Point deployments to new dev cluster

---

.github/workflows/on-push.yaml
.github/workflows/on-release.yaml

Addresses: https://qctrl.atlassian.net/browse/DEVOPS-1244
- Use ci script for cluster auth

ci: Use script for cluster auth

---

docs/conf.py
poetry.lock
pyproject.toml

Addresses: https://qctrl.atlassian.net/browse/PLTFM-3002
- Add new Sphinx theme version to fix HTML validation issue
- Sphinx theme updated with new Docsearch Algolia search bar

fix: Add new Sphinx theme version

---

.github/workflows/on-push.yaml
.github/workflows/on-release.yaml

Addresses: https://qctrl.atlassian.net/browse/ACC-414
- Remove sphinx theme deployments

ci: Remove sphinx theme deployments

---

pyproject.toml

- Update list of `[tool.poetry.urls]` in the `pyproject.toml` to match the one in the `template` repository.

build: Update URL list in pyproject.toml according to template

---

poetry.lock

Addresses: https://github.com/qctrl/open-controls/security/dependabot/22 https://github.com/qctrl/open-controls/security/dependabot/23

build: Bump jinja2
